appPort: 8200
serviceName : "crypto-wallet-adapter"
basePath: ""
AUTHENTICATION_SERVICE_SERVICE_ID: "4b0bde7a-9201-4cf9-859f-e61d976e376d"
AUTHENTICATION_SERVICE_TOKEN: "32e1f6396de342e879ca07ec68d4d907"
SECURITY_BUNDLE_PUBLICKEY : "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZU1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTUFEQ0JpQUtCZ0hYTkxxNzgzaGNHaE95bGlGSzlFTEFZS3YwcApxbWE4ZlBVWmVSOER2Vmc4TllpbVlaa0VoaTBjUDI0ZXA5ZCtRc1dNU1p2dThUdTh3SnlBZ0hWUW5ZREZSenlKClFDYXZ4bG5tQmhoL1RwS2c3anM5TTBlZnNHYW5DQTkrUGRqNnR4RHdPY0RnMTRyZzRwaXRhUnk4YVF5RFl5aEMKTDNDZTg3VitLeDBxYzJPL0FnTUJBQUU9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ=="
authenticationServiceURL: "https://internal.dev.bundlewallet.com/authentication"
keyManagementServiceURL: "https://internal.dev.bundlewallet.com/key-management"
cryptoAdapterServiceURL: "https://internal.dev.bundlewallet.com/crypto-adapter"
depositWebhookURL: "http://internal.dev.bundlewallet.com/crypto-adapter/incoming-deposit"
lockerServiceURL: "https://internal.dev.bundlewallet.com/locker"
purgeCacheInterval: 5
expireCacheDuration: 400
DB_HOST: "127.0.0.1:3306"
DB_USER: ""
DB_PASSWORD: ""
DB_NAME: "walletAdapter"
lockerServicePrefix : "Withdrawal-TXN-"
BTC_SLIP_VALUE: 0
BNB_SLIP_VALUE: 714
ETH_SLIP_VALUE: 60